package gomarker

import "testing"

// TestIsGeneratedRecognisesThePreambleOnly is the security property of both
// exclusions this package serves: a file gets out of the coverage floor, and
// out of the scanned-code boundary, by being generated, so the marker has to
// mean what golang.org/s/generatedcode says it means and nothing looser. The
// "mentioned in a function body" and "mentioned in a doc comment" cases are the
// ones a hand-written file could plausibly hit, deliberately or otherwise --
// the sources on both sides of this package carry the marker text in prose.
func TestIsGeneratedRecognisesThePreambleOnly(t *testing.T) {
	for _, tc := range []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "first line",
			src:  "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage v1\n",
			want: true,
		},
		{
			name: "after a build constraint and blank lines",
			src:  "//go:build !ignore\n\n// Code generated by mockgen. DO NOT EDIT.\n\npackage m\n",
			want: true,
		},
		{
			name: "after a licence header",
			src:  "// Copyright 2026 Example B.V.\n// Code generated by protoc. DO NOT EDIT.\npackage v1\n",
			want: true,
		},
		{
			name: "carriage returns",
			src:  "// Code generated by protoc-gen-go. DO NOT EDIT.\r\n\r\npackage v1\r\n",
			want: true,
		},
		{
			name: "no marker",
			src:  "// Package store persists things.\npackage store\n",
			want: false,
		},
		{
			name: "marker after the package clause",
			src:  "package store\n\n// Code generated by nothing. DO NOT EDIT.\n",
			want: false,
		},
		{
			name: "marker inside a function body",
			src:  "package store\n\nfunc f() string {\n\treturn \"// Code generated by x. DO NOT EDIT.\"\n}\n",
			want: false,
		},
		{
			name: "marker discussed in prose, not asserted",
			src:  "// Package covergate excludes files matching\n// `// Code generated ... DO NOT EDIT.` from the floor.\npackage covergate\n",
			want: false,
		},
		{
			name: "missing the trailing full stop",
			src:  "// Code generated by protoc-gen-go. DO NOT EDIT\n\npackage v1\n",
			want: false,
		},
		{
			name: "indented, so not a marker line",
			src:  "\t// Code generated by protoc-gen-go. DO NOT EDIT.\npackage v1\n",
			want: false,
		},
		{
			name: "empty file",
			src:  "",
			want: false,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := IsGenerated([]byte(tc.src)); got != tc.want {
				t.Errorf("IsGenerated = %v, want %v", got, tc.want)
			}
		})
	}
}
