package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Invariants that hold between measurements rather than inside one of them, and
// the guard on the config key that decides which measurement the module caps are
// applied to.

// TestModuleLOCReconcilesWithUnitLOC keeps the profile's two denominators honest
// against each other. Every line of code in the Go surface resides in exactly
// one module, and inside that module it either resides in a unit or it does not,
// so the module total must equal unit LOC plus non-unit LOC exactly. A drift
// here means one of the two counters has changed meaning, which would show up in
// the report as a property moving for no reason anyone could point at.
func TestModuleLOCReconcilesWithUnitLOC(t *testing.T) {
	idx := load(t, map[string]string{
		"a/a.go": `package a

import "fmt"

// Table resides in no unit.
var Table = []string{"one", "two"}

// F is a unit.
func F() string { return fmt.Sprint(Table) }

// G is another, with a body spanning several lines.
func G(n int) int {
	if n > 1 {
		return n * 2
	}
	return n
}
`,
		"b/b.go": `package b

// H is the only unit here.
func H() int { return 1 }
`,
	}, DefaultConfig())

	set := units(t, idx)
	unitLOC := 0
	for _, u := range set.Units {
		unitLOC += u.LOC
	}
	moduleLOC := 0
	for _, m := range set.Modules {
		moduleLOC += m.LOC
	}

	if moduleLOC != unitLOC+set.NonUnitLOC {
		t.Errorf("module LOC %d != unit LOC %d + non-unit LOC %d (%d): the module denominator "+
			"and the unit denominator have stopped being two views of one measurement",
			moduleLOC, unitLOC, set.NonUnitLOC, unitLOC+set.NonUnitLOC)
	}
}

// TestScannedBoundaryReachesEveryDenominator holds that excluded code leaves
// ALL of the SIG denominators rather than only the unit ones.
//
// It is a real risk rather than a hypothetical: unit size, complexity and
// interfacing are shares of unit LOC, while module coupling and duplication are
// shares of module LOC, and a reader who has only checked the first three has
// checked half the profile. Both come off idx.Files today, so an index-level
// exclusion covers everything by construction — this test is what keeps that
// true if a later measurement ever reads the tree itself.
//
// The fixture uses both exclusion mechanisms because they take effect at
// different points: exclude_dirs skips the directory during the walk, the
// generated marker drops the file after it is parsed. The excluded directory is
// configured rather than defaulted, because the scanner ships no test-only
// exclusions: which packages only tests import is the consuming repository's
// fact to state, and what is under test here is that stating it moves every
// denominator.
func TestScannedBoundaryReachesEveryDenominator(t *testing.T) {
	cfg := DefaultConfig()
	cfg.ExcludeDirs = append(cfg.ExcludeDirs, "internal/storedouble")

	body := func(pkg string) string {
		return "package " + pkg + `

// Padding resides in no unit, so it lands in module LOC and not unit LOC.
var Padding = []string{"one", "two", "three"}

func F(a, b, c, d, e int) int {
	if a > b {
		return c
	}
	return d + e
}
`
	}
	idx := load(t, map[string]string{
		"internal/service/widget/widget.go": body("widget"),
		"internal/storedouble/widget.go":    body("storedouble"),
		"conv/converters.gen.go":            "// Code generated by tools/enumgen. DO NOT EDIT.\n\n" + body("conv"),
	}, cfg)

	set := measured(t, idx, Components{})
	for _, m := range set.Modules {
		if strings.HasPrefix(m.File, "internal/storedouble/") || strings.HasSuffix(m.File, ".gen.go") {
			t.Errorf("module %s is outside the scanned boundary but counts towards the module "+
				"and duplication denominators", m.File)
		}
	}
	if len(set.Modules) != 1 {
		t.Errorf("measured %d modules, want 1: excluded code is still in the module denominator", len(set.Modules))
	}

	// The same boundary, seen from the unit side. If these two ever disagree,
	// one property is being measured over a different codebase than the others.
	unitSet := units(t, idx)
	if len(unitSet.Modules) != len(set.Modules) {
		t.Errorf("unit pass measured %d modules and the module pass %d; the two denominators "+
			"are drawing different boundaries", len(unitSet.Modules), len(set.Modules))
	}
}

// TestConfigRejectsAnUnknownCountingConvention holds that a misspelled value
// fails the run rather than falling back to the default, which would report a
// number the config did not ask for and give no sign of it.
func TestConfigRejectsAnUnknownCountingConvention(t *testing.T) {
	path := filepath.Join(t.TempDir(), "config.json")
	if err := os.WriteFile(path, []byte(`{"module_coupling_counts": "invocations"}`), 0o644); err != nil {
		t.Fatal(err)
	}

	_, err := LoadConfig(path)
	if err == nil {
		t.Fatal("LoadConfig accepted an unknown module_coupling_counts value")
	}
	if !strings.Contains(err.Error(), "module_coupling_counts") {
		t.Errorf("error %q does not name the offending key", err)
	}
}
