package main

import (
	"flag"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The tests in this file drive run() rather than the pieces underneath it,
// because what they pin -- which exit code a caller sees, which file the floor
// is read from, whether the summary is appended or replaced -- are decisions
// run() makes and no unit below it can be wrong about.

// fixtureProfile describes a module that is 8 of 10 hand-written statements,
// 80.00%, alongside a generated file carrying 100 uncovered ones. The two
// denominators are far enough apart that no rounding can confuse them: a run
// that folded generated code back in would report 7.27%, not something one
// digit away from 80.
const fixtureProfile = "mode: set\n" +
	"example.com/m/internal/store/store.go:10.1,12.2 8 1\n" +
	"example.com/m/internal/store/store.go:14.1,16.2 2 0\n" +
	"example.com/m/gen/api.pb.go:1.1,3.2 100 0\n"

// newFixture writes a synthetic module and the profile that describes it. run()
// resolves every name in the profile back to a file on disk to ask whether it
// is generated, so a real directory is the smallest thing that exercises it --
// there is no seam to stub the filesystem out at, and adding one would test the
// seam rather than the tool.
func newFixture(t *testing.T, floor string) (dir, profile string) {
	t.Helper()
	dir = t.TempDir()
	write(t, filepath.Join(dir, "go.mod"), "module example.com/m\n\ngo 1.27.1\n")
	write(t, filepath.Join(dir, "internal", "store", "store.go"), "package store\n")
	write(t, filepath.Join(dir, "gen", "api.pb.go"),
		"// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage gen\n")
	write(t, filepath.Join(dir, defaultFloorFile), floor)

	profile = filepath.Join(dir, "cover.out")
	write(t, profile, fixtureProfile)
	return dir, profile
}

// invoke runs the command the way a shell would, and hands back what it
// printed. The flag set is replaced rather than reset because package-level
// flags can only be registered once and every case here registers them again.
func invoke(t *testing.T, args ...string) (int, string, error) {
	t.Helper()

	savedArgs, savedFlags, savedStdout := os.Args, flag.CommandLine, os.Stdout
	t.Cleanup(func() {
		os.Args, flag.CommandLine, os.Stdout = savedArgs, savedFlags, savedStdout
	})

	flag.CommandLine = flag.NewFlagSet("covergate", flag.ContinueOnError)
	flag.CommandLine.SetOutput(io.Discard)
	os.Args = append([]string{"covergate"}, args...)

	// A file rather than a pipe: the whole report is written before run()
	// returns and nothing is draining the other end, so a pipe would only add a
	// buffer that could fill.
	captured := filepath.Join(t.TempDir(), "stdout")
	f, err := os.Create(captured)
	if err != nil {
		t.Fatalf("capture stdout: %v", err)
	}
	os.Stdout = f

	code, runErr := run()

	os.Stdout = savedStdout
	if err := f.Close(); err != nil {
		t.Fatalf("close capture: %v", err)
	}
	raw, err := os.ReadFile(captured)
	if err != nil {
		t.Fatalf("read capture: %v", err)
	}
	return code, string(raw), runErr
}

// TestRunReportsTheHandWrittenHalf is the tool's whole claim seen from the
// outside: the same profile is 80.00% or 7.27% depending on whether the
// generated file counts, and the report has to quote the first while naming the
// package it left out, so that widening the exclusion is visible on the pull
// request that does it rather than only in the total.
func TestRunReportsTheHandWrittenHalf(t *testing.T) {
	dir, profile := newFixture(t, "50.0\n")

	code, out, err := invoke(t, "-dir", dir, "-profile", profile, "-gate")
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit %d on a run that clears its floor, want 0\n%s", code, out)
	}

	for _, want := range []string{
		"80.00%",                 // 8 of 10, not 8 of 110
		"Excluded as generated:", // and it says so
		"gen",                    // naming the package that left
		"internal/store",         // the hand-written package is listed
		"OK:",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("report is missing %q\n%s", want, out)
		}
	}
	// The generated statements must reach neither half of the ratio. 110 is what
	// the total would read if they did.
	if strings.Contains(out, "110 statements") {
		t.Errorf("generated code reached the denominator\n%s", out)
	}
	// The generated package is named as excluded. It must not also appear in the
	// listing of places to go and write a test, which would be two of the two
	// packages rather than one.
	if !strings.Contains(out, "1 of 1 packages") {
		t.Errorf("the generated package was listed among the packages to test\n%s", out)
	}
}

// TestRunGateOnlyFailsWhenAsked separates two things a caller conflates. Being
// under the floor is a fact about the report and is always printed; the
// non-zero exit is what -gate buys. CI runs the gate, and a developer checking
// where they stand does not -- if the report alone failed, the tool could not
// be run for information.
func TestRunGateOnlyFailsWhenAsked(t *testing.T) {
	dir, profile := newFixture(t, "90.0\n")

	code, out, err := invoke(t, "-dir", dir, "-profile", profile)
	if err != nil {
		t.Fatalf("run without -gate: %v", err)
	}
	if code != 0 {
		t.Errorf("exit %d without -gate, want 0 -- the report is not a failure", code)
	}
	if !strings.Contains(out, "BELOW FLOOR") {
		t.Errorf("report did not say it was below the floor\n%s", out)
	}
	// One statement covers the 80% to 90% gap: ceil(0.9*10) - 8.
	if !strings.Contains(out, "Covering 1 more statements") {
		t.Errorf("report did not quote the shortfall in statements\n%s", out)
	}

	code, _, err = invoke(t, "-dir", dir, "-profile", profile, "-gate")
	if err != nil {
		t.Fatalf("run with -gate: %v", err)
	}
	if code != exitBelowFloor {
		t.Errorf("exit %d under -gate below the floor, want %d", code, exitBelowFloor)
	}
}

// TestRunReadsTheFloorFromTheModuleUnlessTold pins the default that makes the
// single-source claim true: `make cover-api-check` and CI both pass -dir and
// nothing else, so the floor they enforce is whichever file that default names.
// The -floor half is the negative: an explicit path has to win, or the flag is
// decoration.
func TestRunReadsTheFloorFromTheModuleUnlessTold(t *testing.T) {
	// The module's own floor is one the fixture clears and the loose file is one
	// it does not, so the two are told apart by the verdict rather than by
	// trusting the path the report printed.
	dir, profile := newFixture(t, "50.0\n")
	elsewhere := filepath.Join(t.TempDir(), "other-floor")
	write(t, elsewhere, "# a floor kept somewhere else\n95\n")

	_, out, err := invoke(t, "-dir", dir, "-profile", profile)
	if err != nil {
		t.Fatalf("run with the default floor: %v", err)
	}
	if !strings.Contains(out, "50.00%") || !strings.Contains(out, defaultFloorFile) {
		t.Errorf("the default run did not read %s\n%s", defaultFloorFile, out)
	}

	code, out, err := invoke(t, "-dir", dir, "-profile", profile, "-floor", elsewhere, "-gate")
	if err != nil {
		t.Fatalf("run with -floor: %v", err)
	}
	if !strings.Contains(out, "95.00%") {
		t.Errorf("-floor was ignored; the report still quotes the module's own floor\n%s", out)
	}
	if code != exitBelowFloor {
		t.Errorf("exit %d, want %d -- the explicit floor is breached", code, exitBelowFloor)
	}
}

// TestRunAppendsTheSummary covers the reason appendFile opens rather than
// creates. The destination is $GITHUB_STEP_SUMMARY, which several steps of the
// same job write to, so truncating would delete another step's report and the
// loss would show only on the pull request page.
func TestRunAppendsTheSummary(t *testing.T) {
	dir, profile := newFixture(t, "50.0\n")
	summary := filepath.Join(t.TempDir(), "step-summary.md")
	const preexisting = "## An earlier step\n\nwrote this.\n"
	write(t, summary, preexisting)

	for range 2 {
		if _, _, err := invoke(t, "-dir", dir, "-profile", profile, "-summary", summary); err != nil {
			t.Fatalf("run with -summary: %v", err)
		}
	}

	raw, err := os.ReadFile(summary)
	if err != nil {
		t.Fatalf("read summary: %v", err)
	}
	got := string(raw)
	if !strings.HasPrefix(got, preexisting) {
		t.Errorf("the earlier step's content was overwritten\n%s", got)
	}
	if n := strings.Count(got, "## API unit coverage"); n != 2 {
		t.Errorf("summary holds %d reports, want 2 -- the second run replaced rather than appended\n%s", n, got)
	}
	if !strings.Contains(got, "| `internal/store` |") {
		t.Errorf("summary is missing the markdown package table\n%s", got)
	}
}

// TestRunWritesNoSummaryUnlessAsked is the negative half of the one above. The
// flag defaults to empty and the usual local run passes no -summary, so a run
// that wrote a report anyway would be dropping a file into whatever directory
// the developer happened to be standing in.
func TestRunWritesNoSummaryUnlessAsked(t *testing.T) {
	dir, profile := newFixture(t, "50.0\n")

	before, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read fixture dir: %v", err)
	}
	if _, _, err := invoke(t, "-dir", dir, "-profile", profile); err != nil {
		t.Fatalf("run: %v", err)
	}
	after, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read fixture dir: %v", err)
	}
	if len(after) != len(before) {
		t.Errorf("the run left %d entries behind, want %d", len(after), len(before))
	}
}

// TestRunReportsWhyItCouldNotRun keeps every one of these an error rather than
// a zero. Each is a shape a broken invocation actually takes, and a tool that
// answered any of them with "0.00%, floor not met" would send the reader
// looking for missing tests instead of a missing file -- or, under a floor of
// zero, wave the run straight through.
func TestRunReportsWhyItCouldNotRun(t *testing.T) {
	valid, validProfile := newFixture(t, "50.0\n")

	// A directory with no go.mod, so the profile's import paths cannot be turned
	// back into files.
	noModule := t.TempDir()
	write(t, filepath.Join(noModule, defaultFloorFile), "50.0\n")
	write(t, filepath.Join(noModule, "cover.out"), fixtureProfile)

	// A module whose profile names a file no longer on disk, which is what a
	// stale profile kept across a rename looks like.
	stale, staleProfile := newFixture(t, "50.0\n")
	if err := os.Remove(filepath.Join(stale, "internal", "store", "store.go")); err != nil {
		t.Fatalf("remove fixture file: %v", err)
	}

	empty, _ := newFixture(t, "50.0\n")
	emptyProfile := filepath.Join(empty, "empty.out")
	write(t, emptyProfile, "mode: set\n")

	malformed, _ := newFixture(t, "50.0\n")
	malformedProfile := filepath.Join(malformed, "bad.out")
	write(t, malformedProfile, "mode: set\ncoverage: 80.0% of statements\n")

	noFloor, noFloorProfile := newFixture(t, "50.0\n")
	if err := os.Remove(filepath.Join(noFloor, defaultFloorFile)); err != nil {
		t.Fatalf("remove floor: %v", err)
	}

	for _, tc := range []struct {
		name string
		args []string
		want string
	}{
		{
			name: "no arguments at all",
			args: nil,
			want: "-dir and -profile are both required",
		},
		{
			name: "a module with no profile",
			args: []string{"-dir", valid},
			want: "-dir and -profile are both required",
		},
		{
			name: "a profile with no module to resolve it against",
			args: []string{"-profile", validProfile},
			want: "-dir and -profile are both required",
		},
		{
			name: "the floor file is gone",
			args: []string{"-dir", noFloor, "-profile", noFloorProfile},
			want: "read floor",
		},
		{
			name: "no go.mod",
			args: []string{"-dir", noModule, "-profile", filepath.Join(noModule, "cover.out")},
			want: "go.mod",
		},
		{
			name: "the profile was never written",
			args: []string{"-dir", valid, "-profile", filepath.Join(valid, "absent.out")},
			want: "read profile",
		},
		{
			name: "the profile is not a profile",
			args: []string{"-dir", malformed, "-profile", malformedProfile},
			want: "is not a coverage block",
		},
		{
			// A run that compiled nothing writes the header and stops. The ratio
			// would be 0 of 0, which percent() reports as 0.00% -- indistinguish-
			// able from a module whose tests all vanished.
			name: "the profile has a header and nothing else",
			args: []string{"-dir", empty, "-profile", emptyProfile},
			want: "covers no files",
		},
		{
			name: "the profile names a file that is not there",
			args: []string{"-dir", stale, "-profile", staleProfile},
			want: "from profile entry",
		},
		{
			name: "the summary cannot be written",
			args: []string{"-dir", valid, "-profile", validProfile,
				"-summary", filepath.Join(valid, "no-such-directory", "summary.md")},
			want: "write summary",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			code, _, err := invoke(t, tc.args...)
			if err == nil {
				t.Fatalf("run succeeded with exit %d, want an error mentioning %q", code, tc.want)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error = %q, want it to mention %q", err, tc.want)
			}
			// main turns any error into exit 2, so run's own code is not read in
			// that case; returning a breach code beside an error would still be
			// a claim about a measurement that never happened.
			if code != 0 {
				t.Errorf("run returned exit %d alongside an error, want 0", code)
			}
		})
	}
}
